language: php

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6


matrix:
  allow_failures:
    - php: 5.3

before_script:
  - composer install
  - wget http://www.phing.info/get/phing-latest.phar

script: php phing-latest.phar
